[package]
name = "tauri-plugin-prevent-default"
version = "6.0.1"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
categories = ["gui", "web-programming"]
documentation = "https://docs.rs/tauri-plugin-prevent-default"
edition = "2024"
keywords = ["browser", "plugin", "tauri", "webview"]
license = "MIT"
repository = "https://github.com/ferreira-tb/tauri-plugin-prevent-default"
rust-version = "1.90"
description = "Disable default browser shortcuts"

[package.metadata.docs.rs]
no-default-features = true
features = ["platform-windows"]
default-target = "x86_64-unknown-linux-gnu"
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]

[lints.clippy]
clone_on_ref_ptr = "deny"
doc_markdown = "allow"
incompatible_msrv = "deny"
map_unwrap_or = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
needless_borrow = "deny"
rest_pat_in_fully_bound_structs = "deny"
similar_names = "allow"
struct_excessive_bools = "allow"
struct_field_names = "allow"
useless_conversion = "deny"

[lints.clippy.pedantic]
level = "deny"
priority = -1

[dependencies]
bitflags = "2.13"
itertools = "0.15"
thiserror = "2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.strum]
version = "0.28"
features = ["derive"]

[dependencies.tauri]
version = "2.12"
default-features = false

[target."cfg(windows)".dependencies.webview2-com]
version = "0.39"
optional = true

[target."cfg(windows)".dependencies.windows]
version = "0.62"
optional = true

[features]
platform-windows = ["dep:webview2-com", "dep:windows", "tauri/wry"]
