name: Test PR

on:
  pull_request:
    branches: [master]

env:
  RUST_BACKTRACE: 1

concurrency:
  group: test-pr
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Clippy
        run: cargo +nightly clippy
